version: '3'

networks:
  default:
    external:
      name: common

services:
  kontact:
    build:
      context: .
      args:
        buildenv: local

    ports:
      - "8080:8080"

    volumes:
      - ./:/code

    env_file: .env

    command: "pm2-runtime index.js --watch"