version: '3'

services:

  app:

    build:
      context: .
      args:
        buildenv: local

    ports:
      - "8080:8080"

    volumes:
      - ./:/code

    env_file: .env

    command: "pm2-runtime index.js --watch"


  mongodb:

    image: "mongo:latest"
