version: '3'

services:

  app:

    build:
      context: .
      args:
        buildenv: prod

    ports:
      - "8080:8080"

    environment:
      NODE_ENV: production
      HTTP_PORT: 8080
      HTTP_DEBUGMODE: "false"
      APP_URL: http://localhost:8080
      MONGO_CONNECTION: mongodb://mongodb:27017/currency


  mongodb:
    image: "mongo:latest"
